#info = {
#	'arguments': [],	
#	'summary': ""
#}
#async def command(self):
#	pass
#
#close all

rickroll = """MMMMMMMMMMMMMMMWNK00OOkkOO00XNWMMMMMMMMMMMM
MMMMMMMMMMMMMMW0xdoollc::::cldk0NWMMMMMMMMM
MMMMMMMMMMMMMWXxl::;;;;;;;;;::cld0NMMMMMMMM
MMMMMMMMMMMMNKkoc;,,,,,,;;;::c:::oKMMMMMMMM
MMMMMMMMMMMMXOdoccccccllodddxxdl:l0MMMMMMMM
MMMMMMMMMMMMNOooodddxxxxxxxkkkkdlckWMMMMMMM
MMMMMMMMMMMMNxlodddddxxxxxxkkkkxolxNMMMMMMM
MMMMMMMMMMMMWOolooolooodxxddddxxdd0WMMMMMMM
MMMMMMMMMMMMMXxoollllllodxxdddxxdxKWMMMMMMM
MMMMMMMMMMMMWXkddooooooodxkxxxkkxxONMMMMMMM
MMMMMMMMMMMMW0kxdooooooodxxxkkkxxkKWMMMMMMM
MMMMMMMMMMMMMNOxdooooooodxxxkkxxkKWMMMMMMMM
MMMMMMMMMMMMMMNX0kdodddddxxxxxxk0WMMMMMMMMM
MMMMMMMMMMMMMMMMMXxoddddoodxxxxxOKWMMMMMMMM
MMMMMMMMMMMMMMMMMW0dddolllodxxxxkk0KXWMMMMM
MMMMMMMMMMMMMMMMMMNkddolllodxxxxxkxlcdOXNWM
MMMMMMMMMMMMMMMMMMWKxdolcloxxxxxxkx:''';cld
MMMMMMMMMMMMMMMMMMW0xoolclodxxxdxkd;''.....
MMMMMMMMMMMMMMMWNX0xollllloodoodkko;'......
MMMMMMMMMMMMWN0kdxkkdoodddollodkkkd;'......
MMMMMMMMMWNKOoc;;lkOkxxxxxooodkkkd:'.......
MMMMMMMWXOdc;,'.':dkkkkkkxoodxkkx:'........
MMMMWN0xl;,'.....;dkxxxxxdoooloo:'.........
MMMNOl:,'.........;:::clllc:::::,..........
MMM0c'...............';:cc:::::,'..........
MMM0:................',:cc::::;'...........
MMM0:.................':cc:::;,'...........
MMMKl'................';ccc::;,............
MMMXl'.................;ccc::;'............
MMMKc'.................,:::::;'............
MMM0:..................,::;;;,'............
MMM0:..................,:;;,,'............ 
MMMKc..................,:;,'''.............
MMMNo'';:;'............,:;,'''.............
MMMWOooxxo;............,:;,''..............
MMWXOddddc'............,:;,,''.............
MW0dlloodl,............,:;,,''.............
MNkolloodl,............,:;,,,'.............
WKxolllloo;..   .......,;,,,,,.............
Nklcclllol,.     ......,;,''''.............
Kl;,,:cll;..       ....,;....''............
Nd;'..''...        ....,;'.................
WKo,'........       ...,:;,'''.............
MMXx:;;;;;co:.    .....,:::::;;,'..........
MMMWXKKXXXNXc.    .....;::::c:::,.........."""

gif = "https://cdn.discordapp.com/attachments/809437719880663070/858539168895729704/HDRickroll.gif"

info = {
	'arguments': [],
	'summary': "Provides help for general use of the bot or a specific command.",
	'aliases': ['rr'],
}

async def command(self):
	self.delete()
	if self.getArgument(0) == 'gif':
		self.reply(gif)
	else:	
		self.reply(f'`{rickroll}`')

